// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file api/v1/knowledge_search_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/knowledge_search_service.proto.
 */
export const file_api_v1_knowledge_search_service: GenFile = /*@__PURE__*/
  fileDesc("CiVhcGkvdjEva25vd2xlZGdlX3NlYXJjaF9zZXJ2aWNlLnByb3RvEgxtZW1vcy5hcGkudjEipwEKFlNlYXJjaEtub3dsZWRnZVJlcXVlc3QSEgoFcXVlcnkYASABKAlCA+BBAhINCgV0b3BpYxgCIAEoCRIRCglwYWdlX3NpemUYAyABKAUSFAoMY29udGVudF90eXBlGAQgASgJEhMKC2ZpbGVfZm9ybWF0GAUgASgJEhQKDGNyZWF0ZWRfZnJvbRgGIAEoAxIWCg5jcmVhdGVkX2JlZm9yZRgHIAEoAyJyChVLbm93bGVkZ2VTZWFyY2hSZXN1bHQSEAoIZG9jdW1lbnQYASABKAkSDQoFdGl0bGUYAiABKAkSGQoRb3JpZ2luYWxfZmlsZW5hbWUYAyABKAkSDwoHc25pcHBldBgEIAEoCRIMCgRjYXJkGAUgASgJIk8KF1NlYXJjaEtub3dsZWRnZVJlc3BvbnNlEjQKB3Jlc3VsdHMYASADKAsyIy5tZW1vcy5hcGkudjEuS25vd2xlZGdlU2VhcmNoUmVzdWx0Ih8KHVJlYnVpbGRLbm93bGVkZ2VTZWFyY2hSZXF1ZXN0IlIKHlJlYnVpbGRLbm93bGVkZ2VTZWFyY2hSZXNwb25zZRIZChFpbmRleGVkX2RvY3VtZW50cxgBIAEoBRIVCg1pbmRleGVkX2NhcmRzGAIgASgFMr4CChZLbm93bGVkZ2VTZWFyY2hTZXJ2aWNlEoABCg9TZWFyY2hLbm93bGVkZ2USJC5tZW1vcy5hcGkudjEuU2VhcmNoS25vd2xlZGdlUmVxdWVzdBolLm1lbW9zLmFwaS52MS5TZWFyY2hLbm93bGVkZ2VSZXNwb25zZSIggtPkkwIaEhgvYXBpL3YxL2tub3dsZWRnZS9zZWFyY2gSoAEKFlJlYnVpbGRLbm93bGVkZ2VTZWFyY2gSKy5tZW1vcy5hcGkudjEuUmVidWlsZEtub3dsZWRnZVNlYXJjaFJlcXVlc3QaLC5tZW1vcy5hcGkudjEuUmVidWlsZEtub3dsZWRnZVNlYXJjaFJlc3BvbnNlIiuC0+STAiU6ASoiIC9hcGkvdjEva25vd2xlZGdlL3NlYXJjaDpyZWJ1aWxkQrMBChBjb20ubWVtb3MuYXBpLnYxQhtLbm93bGVkZ2VTZWFyY2hTZXJ2aWNlUHJvdG9QAVowZ2l0aHViLmNvbS91c2VtZW1vcy9tZW1vcy9wcm90by9nZW4vYXBpL3YxO2FwaXYxogIDTUFYqgIMTWVtb3MuQXBpLlYxygIMTWVtb3NcQXBpXFYx4gIYTWVtb3NcQXBpXFYxXEdQQk1ldGFkYXRh6gIOTWVtb3M6OkFwaTo6VjFiBnByb3RvMw", [file_google_api_annotations, file_google_api_field_behavior]);

/**
 * @generated from message memos.api.v1.SearchKnowledgeRequest
 */
export type SearchKnowledgeRequest = Message<"memos.api.v1.SearchKnowledgeRequest"> & {
  /**
   * @generated from field: string query = 1;
   */
  query: string;

  /**
   * @generated from field: string topic = 2;
   */
  topic: string;

  /**
   * @generated from field: int32 page_size = 3;
   */
  pageSize: number;

  /**
   * @generated from field: string content_type = 4;
   */
  contentType: string;

  /**
   * @generated from field: string file_format = 5;
   */
  fileFormat: string;

  /**
   * @generated from field: int64 created_from = 6;
   */
  createdFrom: bigint;

  /**
   * @generated from field: int64 created_before = 7;
   */
  createdBefore: bigint;
};

/**
 * Describes the message memos.api.v1.SearchKnowledgeRequest.
 * Use `create(SearchKnowledgeRequestSchema)` to create a new message.
 */
export const SearchKnowledgeRequestSchema: GenMessage<SearchKnowledgeRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_knowledge_search_service, 0);

/**
 * @generated from message memos.api.v1.KnowledgeSearchResult
 */
export type KnowledgeSearchResult = Message<"memos.api.v1.KnowledgeSearchResult"> & {
  /**
   * @generated from field: string document = 1;
   */
  document: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string original_filename = 3;
   */
  originalFilename: string;

  /**
   * @generated from field: string snippet = 4;
   */
  snippet: string;

  /**
   * @generated from field: string card = 5;
   */
  card: string;
};

/**
 * Describes the message memos.api.v1.KnowledgeSearchResult.
 * Use `create(KnowledgeSearchResultSchema)` to create a new message.
 */
export const KnowledgeSearchResultSchema: GenMessage<KnowledgeSearchResult> = /*@__PURE__*/
  messageDesc(file_api_v1_knowledge_search_service, 1);

/**
 * @generated from message memos.api.v1.SearchKnowledgeResponse
 */
export type SearchKnowledgeResponse = Message<"memos.api.v1.SearchKnowledgeResponse"> & {
  /**
   * @generated from field: repeated memos.api.v1.KnowledgeSearchResult results = 1;
   */
  results: KnowledgeSearchResult[];
};

/**
 * Describes the message memos.api.v1.SearchKnowledgeResponse.
 * Use `create(SearchKnowledgeResponseSchema)` to create a new message.
 */
export const SearchKnowledgeResponseSchema: GenMessage<SearchKnowledgeResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_knowledge_search_service, 2);

/**
 * @generated from message memos.api.v1.RebuildKnowledgeSearchRequest
 */
export type RebuildKnowledgeSearchRequest = Message<"memos.api.v1.RebuildKnowledgeSearchRequest"> & {
};

/**
 * Describes the message memos.api.v1.RebuildKnowledgeSearchRequest.
 * Use `create(RebuildKnowledgeSearchRequestSchema)` to create a new message.
 */
export const RebuildKnowledgeSearchRequestSchema: GenMessage<RebuildKnowledgeSearchRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_knowledge_search_service, 3);

/**
 * @generated from message memos.api.v1.RebuildKnowledgeSearchResponse
 */
export type RebuildKnowledgeSearchResponse = Message<"memos.api.v1.RebuildKnowledgeSearchResponse"> & {
  /**
   * @generated from field: int32 indexed_documents = 1;
   */
  indexedDocuments: number;

  /**
   * @generated from field: int32 indexed_cards = 2;
   */
  indexedCards: number;
};

/**
 * Describes the message memos.api.v1.RebuildKnowledgeSearchResponse.
 * Use `create(RebuildKnowledgeSearchResponseSchema)` to create a new message.
 */
export const RebuildKnowledgeSearchResponseSchema: GenMessage<RebuildKnowledgeSearchResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_knowledge_search_service, 4);

/**
 * @generated from service memos.api.v1.KnowledgeSearchService
 */
export const KnowledgeSearchService: GenService<{
  /**
   * @generated from rpc memos.api.v1.KnowledgeSearchService.SearchKnowledge
   */
  searchKnowledge: {
    methodKind: "unary";
    input: typeof SearchKnowledgeRequestSchema;
    output: typeof SearchKnowledgeResponseSchema;
  },
  /**
   * @generated from rpc memos.api.v1.KnowledgeSearchService.RebuildKnowledgeSearch
   */
  rebuildKnowledgeSearch: {
    methodKind: "unary";
    input: typeof RebuildKnowledgeSearchRequestSchema;
    output: typeof RebuildKnowledgeSearchResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_knowledge_search_service, 0);

